// add a head section
export default function Head() {
  return (
    <head>
      <title>Ghita's Blogs</title>
      <meta name="description" content="Generated by Next.js" />
      <link rel="icon" href="/favicon.ico" />
    </head>
  )
}
