import Link from "next/link"
import Head from "./head"
import "@/styles/global.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const header = (
    <header>
      <Link href="/">
        <h1 className="text-3x1 font-bold underline">Ghita's blog</h1>
      </Link>
      <p>Welcome to my tech blog</p>
    </header>
  )

  const footer = (
    <footer>
      <div>
        <br />
        <h3>Developed by Ghita</h3>
      </div>
    </footer>
  )

  return (
    <html lang="en">
      <body>
        {header}
        {children}
        {footer}
      </body>
    </html>
  )
}
