name: Build, Export and Publish Next.js App
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    name: Build Next.js
    steps:
    - uses: actions/checkout@v3
    - id: Build-Next
      uses: ricardobiundo/NextPagesAction@1.0.2
      with:
        username: 'ghita'
        reponame: 'blog'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
    