name: Build, Export and Publish Next.js App
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_next:
    runs-on: ubuntu-latest
    name: Build Next.js
    steps:
    - uses: actions/checkout@v3
    - id: Build-Next
      uses: ricardobiundo/NextPagesAction@1.0.2
      with:
        username: 'ghita'
        reponame: 'blog'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged